# Generated by Django 5.1.1 on 2024-09-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consertos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consertodemoto",
            name="moto_id",
            field=models.IntegerField(default=0),
        ),
    ]
