# Generated by Django 5.0.3 on 2024-09-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mecanico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.IntegerField()),
                ("tempo_por_dia", models.IntegerField(default=8)),
                ("nivel_complexidade", models.IntegerField()),
            ],
        ),
    ]
